-- Infodrop Pyrénées V1
-- Migration additive : aucune table historique n'est supprimée ou renommée.

create table if not exists public.regional_sources (
  slug text primary key,
  name text not null,
  publisher text,
  homepage_url text not null,
  feed_url text,
  source_type text not null,
  scope text not null,
  default_zone text,
  default_locality text,
  requires_keyword boolean not null default true,
  language text not null default 'fr',
  automation text not null default 'manual-review',
  verification text not null default 'to-verify',
  active boolean not null default false,
  registry_verified_at date,
  last_checked_at timestamptz,
  last_success_at timestamptz,
  last_status text,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint regional_sources_zone_check
    check (default_zone is null or default_zone in ('core', 'functional_ring', 'cross_border')),
  constraint regional_sources_automation_check
    check (automation in ('rss', 'manual-review', 'adapter-needed', 'official-api-to-study'))
);

create table if not exists public.regional_source_checks (
  id bigint generated by default as identity primary key,
  source_slug text not null references public.regional_sources(slug) on update cascade on delete cascade,
  checked_at timestamptz not null default now(),
  status text not null,
  response_ms integer,
  articles_seen integer not null default 0,
  error_message text,
  constraint regional_source_checks_status_check
    check (status in ('ok', 'timeout', 'error'))
);

alter table public.actu add column if not exists edition_slug text not null default 'national';
alter table public.actu add column if not exists territory_zone text;
alter table public.actu add column if not exists locality text;
alter table public.actu add column if not exists category text;
alter table public.actu add column if not exists source_kind text;
alter table public.actu add column if not exists source_slug text;
alter table public.actu add column if not exists canonical_url text;
alter table public.actu add column if not exists is_paywalled boolean not null default false;
alter table public.actu add column if not exists ingested_at timestamptz not null default now();
alter table public.user_read_articles add column if not exists edition_slug text not null default 'national';
alter table public.user_bookmarks add column if not exists edition_slug text not null default 'national';

update public.actu
set canonical_url = url
where canonical_url is null;

update public.user_read_articles as reads
set edition_slug = case when actu.edition_slug = 'pyrenees' then 'pyrenees' else 'national' end
from public.actu as actu
where reads.article_id = actu.id;

update public.user_bookmarks as bookmarks
set edition_slug = case when actu.edition_slug = 'pyrenees' then 'pyrenees' else 'national' end
from public.actu as actu
where bookmarks.article_id = actu.id;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'actu_territory_zone_check'
      and conrelid = 'public.actu'::regclass
  ) then
    alter table public.actu
      add constraint actu_territory_zone_check
      check (territory_zone is null or territory_zone in ('core', 'functional_ring', 'cross_border'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'actu_source_slug_fkey'
      and conrelid = 'public.actu'::regclass
  ) then
    alter table public.actu
      add constraint actu_source_slug_fkey
      foreign key (source_slug) references public.regional_sources(slug)
      on update cascade on delete set null;
  end if;
end $$;

create index if not exists idx_actu_edition_heure
  on public.actu (edition_slug, heure desc);

create index if not exists idx_actu_pyrenees_zone_heure
  on public.actu (territory_zone, heure desc)
  where edition_slug = 'pyrenees';

create index if not exists idx_actu_source_slug
  on public.actu (source_slug)
  where source_slug is not null;

create index if not exists idx_regional_source_checks_source_time
  on public.regional_source_checks (source_slug, checked_at desc);

create index if not exists idx_user_read_articles_edition
  on public.user_read_articles (user_id, edition_slug, read_at desc);

create index if not exists idx_user_bookmarks_edition
  on public.user_bookmarks (user_id, edition_slug, created_at desc);

alter table public.regional_sources enable row level security;
alter table public.regional_source_checks enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'regional_sources'
      and policyname = 'regional_sources_public_read'
  ) then
    create policy regional_sources_public_read
      on public.regional_sources
      for select
      to anon, authenticated
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'regional_source_checks'
      and policyname = 'regional_source_checks_public_read'
  ) then
    create policy regional_source_checks_public_read
      on public.regional_source_checks
      for select
      to anon, authenticated
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'actu'
      and policyname = 'actu_pyrenees_public_read'
  ) then
    create policy actu_pyrenees_public_read
      on public.actu
      for select
      to anon, authenticated
      using (edition_slug = 'pyrenees');
  end if;
end $$;

comment on table public.regional_sources is
  'Registre observable des sources de l édition locale Infodrop Pyrénées.';

comment on table public.regional_source_checks is
  'Historique technique des lectures de sources régionales, sans données personnelles.';

comment on column public.actu.edition_slug is
  'Edition éditoriale : national pour l existant, pyrenees pour la V1 locale.';

comment on column public.actu.territory_zone is
  'core, functional_ring ou cross_border pour la qualification territoriale.';

comment on column public.user_read_articles.edition_slug is
  'Sépare les lectures nationales et pyrénéennes lors de la synchronisation facultative.';

comment on column public.user_bookmarks.edition_slug is
  'Sépare les favoris nationaux et pyrénéens lors de la synchronisation facultative.';
